name: CD flow - Build & Publish

on:
  push:
    branches:
      - main

jobs:
  docker-build-api:
    name: Docker release - rfjs-api
    uses: royfuwei/rf-devops/.github/workflows/_release-docker.yml@main
    with:
      projectName: rfjs-api
      projectSource: royfuwei
      version: latest
      buildPath: apps/api/Dockerfile
      environment: k8s-rfjs-api
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      envPAT: ${{ secrets.GIT_TOKEN }}
      
  docker-build-web:
    name: Docker release - rfjs-web
    uses: royfuwei/rf-devops/.github/workflows/_release-docker.yml@main
    with:
      projectName: rfjs-web
      projectSource: royfuwei
      version: latest
      buildPath: apps/web/Dockerfile
      environment: k8s-rfjs-api
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      envPAT: ${{ secrets.GIT_TOKEN }}

  helm-release:
    needs: [docker-build-api, docker-build-web]
    name: Helm release - rfjs
    uses: royfuwei/rf-devops/.github/workflows/_release-helm.yml@main
    with:
      config-path: .github/labeler.yml
      projectName: rfjs
      projectSource: royfuwei
      appVersion: latest
      helmVersion: 0.0.${{ github.run_number }}
      environment: k8s-rfjs-api
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      envPAT: ${{ secrets.GIT_TOKEN }}

  # deploy-rfjs-api:
  #   needs: helm-release
  #   name: Deploy local k8s - rfjs-api
  #   uses: royfuwei/rf-devops/.github/workflows/rfjs-api-deploy-k8s.yml@main
  #   with:
  #     projectName: rfjs-api
  #     projectSource: royfuwei
  #     environment: k8s-rfjs-api
  #   secrets:
  #     HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
  #     HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  #     HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
  #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  #     envPAT: ${{ secrets.GIT_TOKEN }}
  #     ENV_DB_MONGO_URI: ${{ secrets.ENV_DB_MONGO_URI }}
  #     ENV_PUBLIC_SUPABASE_URL: ${{ secrets.ENV_PUBLIC_SUPABASE_URL }}
  #     ENV_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.ENV_PUBLIC_SUPABASE_ANON_KEY }}
  #     ENV_LINE_CHANNEL_ID: ${{ secrets.ENV_LINE_CHANNEL_ID }}
  #     ENV_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.ENV_LINE_CHANNEL_ACCESS_TOKEN }}
  #     ENV_LINE_CHANNEL_SECRET: ${{ secrets.ENV_LINE_CHANNEL_SECRET }}
  #     ENV_LINE_NOTIFY_CLIENT_ID: ${{ secrets.ENV_LINE_NOTIFY_CLIENT_ID }}
  #     ENV_LINE_NOTIFY_CLIENT_SECRET: ${{ secrets.ENV_LINE_NOTIFY_CLIENT_SECRET }}

  deploy-rfjs:
    needs: helm-release
    name: Deploy local k8s - rfjs
    uses: royfuwei/rf-devops/.github/workflows/rfjs-deploy-k8s.yml@main
    with:
      projectName: rfjs
      projectSource: royfuwei
      environment: k8s-rfjs-api
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      envPAT: ${{ secrets.GIT_TOKEN }}
      ENV_DB_MONGO_URI: ${{ secrets.ENV_DB_MONGO_URI }}
      ENV_PUBLIC_SUPABASE_URL: ${{ secrets.ENV_PUBLIC_SUPABASE_URL }}
      ENV_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.ENV_PUBLIC_SUPABASE_ANON_KEY }}
      ENV_LINE_CHANNEL_ID: ${{ secrets.ENV_LINE_CHANNEL_ID }}
      ENV_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.ENV_LINE_CHANNEL_ACCESS_TOKEN }}
      ENV_LINE_CHANNEL_SECRET: ${{ secrets.ENV_LINE_CHANNEL_SECRET }}
      ENV_LINE_NOTIFY_CLIENT_ID: ${{ secrets.ENV_LINE_NOTIFY_CLIENT_ID }}
      ENV_LINE_NOTIFY_CLIENT_SECRET: ${{ secrets.ENV_LINE_NOTIFY_CLIENT_SECRET }}
