name: CD Production

on:
  pull_request_target:
    branches:
      - production
    types:
      - closed

jobs:
  run-ci:
    name: Run CI flow
    uses: ./.github/workflows/run-ci.yml
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

  run-release:
    name: Release Production
    uses: ./.github/workflows/node-release.yml
    needs: run-ci
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}