name: CI flow - Nx

on:
  push:
    branches:
      - main

jobs:
  ci-with-nx:
    name: CI with NX
    runs-on: ubuntu-latest
    environment: actions
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RFJS_GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: 'setSHAs'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main

      - name: Install dependencies
        run: npm ci

      - name: Run NX run-many lint, test, and tsc
        run: |
          npx nx run-many --all \
            --target=lint,tsc,test \ 
            --passWithNoTests \
            --parallel=5