name: CI flow on push

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'

jobs:
  run-ci:
    name: Run CI flow
    uses: ./.github/workflows/run-ci.yml
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}