name: Deploy local k8s

on:
  workflow_call:
    inputs:
      appVersion:
        type: string
        default: latest
      helmVersion:
        type: string
        default: 0.0.1
      environment:
        type: string
        default: k8s-rfjs
    secrets:
      GIT_TOKEN:
        required: true
      KUBE_CONFIG:
        required: true
      HARBOR_HOST:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_TOKEN:
        required: true
      # env secrets
      ENV_DB_MONGO_URI:
        required: true
      ENV_PUBLIC_SUPABASE_URL:
        required: true
      ENV_PUBLIC_SUPABASE_ANON_KEY:
        required: true
      ENV_LINE_CHANNEL_ID:
        required: true
      ENV_LINE_CHANNEL_ACCESS_TOKEN:
        required: true
      ENV_LINE_CHANNEL_SECRET:
        required: true
      ENV_LINE_NOTIFY_CLIENT_ID:
        required: true
      ENV_LINE_NOTIFY_CLIENT_SECRET:
        required: true

jobs:
  docker-build-api:
    name: Docker release - rfjs-api:${{ inputs.appVersion }}
    uses: royfuwei/rf-devops/.github/workflows/_release-docker.yml@main
    with:
      projectName: rfjs-api
      projectSource: royfuwei
      version: ${{ inputs.appVersion }}
      buildPath: apps/api/Dockerfile
      environment: ${{ inputs.environment }}
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      envPAT: ${{ secrets.GIT_TOKEN }}
      
  docker-build-web:
    name: Docker release - rfjs-web:${{ inputs.appVersion }}
    uses: royfuwei/rf-devops/.github/workflows/_release-docker.yml@main
    with:
      projectName: rfjs-web
      projectSource: royfuwei
      version: ${{ inputs.appVersion }}
      buildPath: apps/web/Dockerfile
      environment: ${{ inputs.environment }}
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      envPAT: ${{ secrets.GIT_TOKEN }}

  helm-release:
    needs: [docker-build-api, docker-build-web]
    name: Helm release - rfjs:${{ inputs.helmVersion }}
    uses: royfuwei/rf-devops/.github/workflows/_release-helm.yml@main
    with:
      projectName: rfjs
      projectSource: royfuwei
      appVersion: ${{ inputs.appVersion }}
      helmVersion: ${{ inputs.helmVersion }}
      environment: ${{ inputs.environment }}
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      envPAT: ${{ secrets.GIT_TOKEN }}

  deploy-rfjs:
    needs: helm-release
    name: Deploy local k8s - rfjs
    uses: royfuwei/rf-devops/.github/workflows/rfjs-deploy-k8s.yml@main
    with:
      projectName: rfjs
      projectSource: royfuwei
      environment: ${{ inputs.environment }}
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      envPAT: ${{ secrets.GIT_TOKEN }}
      ENV_DB_MONGO_URI: ${{ secrets.ENV_DB_MONGO_URI }}
      ENV_PUBLIC_SUPABASE_URL: ${{ secrets.ENV_PUBLIC_SUPABASE_URL }}
      ENV_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.ENV_PUBLIC_SUPABASE_ANON_KEY }}
      ENV_LINE_CHANNEL_ID: ${{ secrets.ENV_LINE_CHANNEL_ID }}
      ENV_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.ENV_LINE_CHANNEL_ACCESS_TOKEN }}
      ENV_LINE_CHANNEL_SECRET: ${{ secrets.ENV_LINE_CHANNEL_SECRET }}
      ENV_LINE_NOTIFY_CLIENT_ID: ${{ secrets.ENV_LINE_NOTIFY_CLIENT_ID }}
      ENV_LINE_NOTIFY_CLIENT_SECRET: ${{ secrets.ENV_LINE_NOTIFY_CLIENT_SECRET }}
