name: Invoke Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: royfuwei/rf-devops/.github/workflows/reusable-workflow.yml@main
    with:
      example_input: "World"
